version: '3.8'

services:
  mysql:
    container_name: stock_mysql
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=stock
      - MYSQL_USER=local_user
      - MYSQL_PASSWORD=LOCAL_TEST
      - MYSQL_ROOT_PASSWORD=LOCAL_TEST
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: stock_redis
    hostname: stock_redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
