spring:
    datasource:
        url: jdbc:mysql://localhost:3308/stock
        username: local_user
        password: LOCAL_TEST
        hikari:
            maximum-pool-size: 50
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                default_schema: stock
        open-in-view: false
    data:
        redis:
            host: localhost
            port: 6379


