spring:
    datasource:
        url: jdbc:mysql://localhost:3308/stock
        username: local_user
        password: LOCAL_TEST
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true
                default_schema: stock
        open-in-view: false